spring:
  profiles:
    active: native
  application:
    name:
      config-server
  cloud:
    config:
      server:
        native:
          # The classpath is in the /resources/configurations folder in the config-server project.
          search-locations: classpath:/configurations

server:
  port: 8888
