server:
  port: 8222

spring:
  cloud:
    gateway:
      # I want the gateway to discover the services from Eureka.
      discovery:
        locator:
          enabled: true
      # The routes for each microservice. The lb shows the microservices should be load balanced.
      routes:
        - id: customer-service
          # In uppercase letters based on how it is registered in Eureka. In case we have many instances of the same service, it will load balance between them.
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**

        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**

        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**

          # Requests going to the order-lines are redirected to the order-service
        - id: order-line-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-ines/**

        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**

        - id: notification-service
          uri: lb:http://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**



