spring:
  application:
    name: payment-service
  config:
    import: configserver:http://config-server:8888
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://discovery-service:8761/eureka/
