server:
  port: 8040

spring:
  application:
    name: notification-service

  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://discovery-service:8761/eureka/

  data:
    mongodb:
      username: eugene
      password: eugene
      host: mongodb
      port: 27017
      database: notification-service
      authentication-database: admin



  kafka:
    consumer:
      bootstrap-servers: kafka:29092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        # spring.json.type.mapping: orderConfirmationDTO:com.eugene.order_service.kafka.OrderConfirmationDTO,paymentConfirmationDTO:com.eugene.payment_service.kafkaproducer.PaymentConfirmationDTO
        # Send the orderConfirmationDTO object from the path in the notification-service and paymentConfirmationDTO from the path in the payment-service as well.
        spring.json.type.mapping: orderConfirmationDTO:com.eugene.notificationservice.kafka.order.OrderConfirmationDTO,paymentConfirmationDTO:com.eugene.notificationservice.kafka.payment.PaymentConfirmationDTO



