server:
  port: 8070

spring:
  application:
    name: payment-service

  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://discovery-service:8761/eureka/

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/ecommercePaymentService
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmationDTO:com.eugene.payment_service.kafkaproducer.PaymentConfirmationDTO

application:
  config:
    product-url: http://api-gateway:8222/api/v1/products