server:
  port: 8050

spring:

  application:
    name: product-service

  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://discovery-service:8761/eureka/

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/ecommerceProductService
    username: postgres
    password: root

  jpa:
    hibernate:
      # Validate because fly-way will create the schema for us
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect