spring:
  application:
    name: notification-service
  mail:
    host: localhost
    port: 1025
    username: eugene
    password: eugene
    properties:
      mail.smtp.auth: true
#      mail.smtp.auth: false
      mail.smtp.starttls.enable: true
#      mail.smtp.starttls.enable: false
      mail.smtp.trust: "*"
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000
  config:
    import: optional:configserver:http://localhost:8888
